baseURL = 'https://www.largerworld.cc/'
languageCode = 'zh-cn'
title = '天想'
mainSections = ["archives"]
defaultContentLanguage = "zh"
copyright = "© 2025 ffha. All Rights Reserved."
hasCJKLanguage = true

[[module.mounts]]
source = 'static'
target = 'static'
excludeFiles = '.gitkeep'
[[module.imports]]
path = 'github.com/adityatelange/hugo-PaperMod'

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
defaultTheme = "auto"
author = 'Alan Feng'
ShowReadingTime = true
[params.assets]
disableHLJS = true
[params.homeInfoParams]
Title = "天想"
Content = '碎碎念罢了。和尚念经罢了。'
[[params.socialIcons]]
name = 'github'
url = 'https://github.com/ffha'
[[params.socialIcons]]
name = 'X'
url = 'https://x.com/ffha090124'
[[params.socialIcons]]
name = 'bluesky'
url = 'https://bsky.app/profile/largerworld.cc'
[[params.socialIcons]]
name = 'RSS'
url = '/index.xml'
[[params.socialIcons]]
name = 'matrix'
url = 'https://matrix.to/#/@fthasdd:lunacia.cc'
[[params.socialIcons]]
name = 'bilibili'
url = 'https://space.bilibili.com/616301951'

[markup.goldmark.renderer]
unsafe = true
hardWraps = true

[markup.highlight]
style = "github"

[[menu.main]]
name = '搜索'
pageRef = '/search'
[[menu.main]]
name = '存档'
pageRef = '/archives'

[[menu.main]]
name = '关于'
pageRef = '/about'